version: '3.2'

services:

  scrum8-ocr:
    build: ./scrum8-ocr
    ports:
      - "8081:8081"

  scrum8-services:
    build: ./scrum8-services
    ports:
      - "8082:8082"

  jira:
    image: cptactionhank/atlassian-jira:latest
    ports:
      - 8080:8080
      - "8080:8080"
    volumes:
      - ./home/:/var/atlassian/jira
      - ./log/:/opt/atlassian/jira/logs
      - ./build/jira/home/:/var/atlassian/jira
      - ./build/jira/log/:/opt/atlassian/jira/logs

  portainer:
    image: portainer/portainer:latest