version: '3.2'

services:

  scrum8-ocr:
    build: ./scrum8-ocr
    ports:
      - "8081:8081"

  jira:
    image: cptactionhank/atlassian-jira:latest
    ports:
      - 8080:8080
    volumes:
      - ./home/:/var/atlassian/jira
      - ./log/:/opt/atlassian/jira/logs

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"